version: "3"
services:
  app:
    image: ruby-mysql-socket
    ports:
      - 3000:3000
    volumes:
      - .:/app
    external_links:
      - db
    networks:
      - database
    tty: true
networks:
  database:
    external:
      # External network name, automatically named with docker-compose
      # to <mariadb_directory>_default. Run `docker networks ls` for
      # the list.
      name: mariadb_default
